### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by JOY** [smitt04/slack-dark-theme#2]
Hi. In Windows, there is no 'chmod'. Here is the result of the command:
![image](https://user-images.githubusercontent.com/5027251/61327253-afaa6b00-a842-11e9-9a14-851b3d36e9d4.png)

**Comment by smitt04** [comment]
Ah it looks like @guyhalestorm used https://github.com/laurent22/wslpath

If someone can find a way to get the correct WIN_HOME without that dependency then  I can update it. I don't have a way to test windows at the moment, maybe later.

**Comment by mJace** [comment]
When using Ubuntu WSL in win10, you can not just access the C by `/c`,  the correct path is `/mnt/c`
Also, I don't know why this returns null for WIN_HOME_RAW.
`WIN_HOME_RAW="$(cmd.exe /mnt/c "<nul set /p=%UserProfile%" 2>/dev/null)"`
So I modify the WIN_HOME for `/mnt/c/Users/<UsrName>`  

But after I finally let the script to run successfully. I got this error when I try to run Slack

![image](https://user-images.githubusercontent.com/9836691/61344847-57488d00-a885-11e9-84a2-533b532d48ee.png)

**Comment by smitt04** [comment]
Updated windows script to not have wslpath dependency, seems to work for me, please test.

**Comment by JOY** [comment]
Sorry but i don't get it. Should I use Ubuntu WSL in win10 to run the script or PowerShell?
PowerShell doesn't work in my case.

**Comment by smitt04** [comment]
This has only been tested on Ubuntu WSL. It is not a power shell script. 

@tarantulae made a power shell script here https://github.com/tarantulae/slack-black-theme-4.0PS
