### ISSUE TITLE
Editing a message results in white text on a white background

### ISSUE THREAD

**Issue by cameronmccord2** [smitt04/slack-dark-theme#3]
Steps to reproduce:
1. Send a message
2. Edit the message
3. Cannot see the text

Result:
<img width="1376" alt="Screen Shot 2019-07-16 at 2 29 04 PM" src="https://user-images.githubusercontent.com/2424811/61327420-1d6c7d80-a7d6-11e9-83e4-32f16cdf22a9.png">

Result with text highlighted to show it is really there:
<img width="1364" alt="Screen Shot 2019-07-16 at 2 29 11 PM" src="https://user-images.githubusercontent.com/2424811/61327419-1d6c7d80-a7d6-11e9-9588-549106749cde.png">

**Comment by smitt04** [comment]
This has been fixed in the upstream, refresh slack to see changes.
